version: "3"

services:
  # Redis 서비스
  redis:
    image: redis:latest
    container_name: redis_beauty4u
    ports:
      - "${REDIS_PORT}:6379"


  # Zookeeper 서비스
  zookeeper:
    image: wurstmeister/zookeeper
    container_name: zookeeper
    ports:
      - "2181:2181"

  # Kafka 서비스
  kafka:
    image: wurstmeister/kafka
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: localhost
      KAFKA_CREATE_TOPICS: "Topic:1:1"
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
      - /var/run/docker.sock
    depends_on:
      - zookeeper

 # elk 서비스 - elasticsearch, kibana, logstash
#  OpenSearch 로 변경
  opensearch:
    container_name: opensearch_beauty4u
    build:
      context: .
      dockerfile: Dockerfile
      args:
        VERSION: 2.11.0
    environment:
      - discovery.type=single-node
      - "OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m"
      - bootstrap.memory_lock=true # 메모리 스왑 방지
      - plugins.security.disabled=true # 개발 환경용 보안 해제
      - DISABLE_INSTALL_DEMO_CONFIG=true  # 데모 설정 비활성화
      - "network.host=0.0.0.0" # 모든 네트워크 인터페이스에서 접속 가능하도록
    ulimits: # 메모리 락 설정을 위한 ulimits 추가
      memlock:
        soft: -1
        hard: -1
    ports:
      - "${OPENSEARCH_PORT}:9200"
    volumes:
      - ./opensearch-data:/usr/share/opensearch/data
    networks:
      - elk

# OpenSearch Dashboards - 키바나 대체
  opensearch-dashboards:
    container_name: opensearch_dashboards_beauty4u
    image: opensearchproject/opensearch-dashboards:2.11.0
    environment:
      OPENSEARCH_HOSTS: '["http://opensearch:9200"]'
      OPENSEARCH_ALLOW_INSECURE: 'true'
      DISABLE_SECURITY_DASHBOARDS_PLUGIN: "true"  # 보안 플러그인 비활성화
      PLUGINS_SECURITY_DISABLED: "true"           # 보안 기능 비활성화
    ports:
      - 5601:5601
    depends_on:
      - opensearch
    networks:
      - elk

  logstash:
    container_name: logstash_beauty4u
    image: opensearchproject/logstash-oss-with-opensearch-output-plugin:8.9.0  # OpenSearch 호환 이미지로 변경
    environment:
      - LS_JAVA_OPTS=-Xmx256m -Xms256m  # JVM 힙 사이즈 설정
      - OPENSEARCH_USER=${OPENSEARCH_USER}
      - OPENSEARCH_PASSWORD=${OPENSEARCH_PASSWORD}
    ports:
      - 5000:5000
    volumes:
      - ./logstash/pipeline:/usr/share/logstash/pipeline
    depends_on:
      - opensearch
    networks:
      - elk

networks:
  elk:
    driver: bridge

