server:
  port: 8080

spring:
  application:
    name: beauty4u
  config:
    import: optional:file:.env[.properties]
  datasource:
    url: jdbc:mariadb://${MARIADB_HOST}:${MARIADB_PORT}/${MARIADB_DATABASE}
    username: ${MARIADB_USER}
    password: ${MARIADB_PASSWORD}
    driver-class-name: ${DRIVER_CLASS_NAME}

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  # 엘라스틱서치 최초 설치 시 기본 계정
  elasticsearch:
    uris: ${ELASTIC_URIS}
    username: ${ELASTIC_USER}
    password: ${ELASTIC_PASSWORD}


token:
  expiration_time: 7200000
  secret: ${SECRET_KEY}

springdoc:
  swagger-ui:
    path: /