server:
  port: 8080


spring:
  application:
    name: beauty4u
  servlet:
    multipart:
      max-file-size: 10MB   # 개별 파일의 최대 크기
      max-request-size: 10MB # 전체 요청의 최대 크기
  config:
    import: optional:file:.env[.properties]
  datasource:
    url: jdbc:mariadb://${MARIADB_HOST}:${MARIADB_PORT}/${MARIADB_DATABASE}
    username: ${MARIADB_USER}
    password: ${MARIADB_PASSWORD}
    driver-class-name: ${DRIVER_CLASS_NAME}
  data:
    mongodb:
      uri: mongodb+srv://${MONGODB_USER}:${MONGODB_PASSWORD}@cluster0.avtro.mongodb.net/${MONGODB_DATABASE}?retryWrites=true&w=majority
    elasticsearch:
      repositories:
        enabled: false


  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  # 엘라스틱서치 최초 설치 시 기본 계정
  elasticsearch:
    uris: ${ELASTIC_URIS}
    username: ${ELASTIC_USER}
    password: ${ELASTIC_PASSWORD}
    goods:
      index:
        name: goods
    reviews:
      index:
        name: reviews

  mail:
    host: ${MAIL_HOST}
    port: ${MAIL_PORT}
    username: ${MAIL_USER}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000
    auth-code-expiration-millis: 300000

mybatis:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: mapper/**/*.xml
  type-aliases-package: com.beauty4u.backend.**

token:
  access-token-expiration-time: ${ACCESS_TOKEN_EXPIRATION_TIME}
  refresh-token-expiration-time: ${REFRESH_TOKEN_EXPIRATION_TIME}
  secret: ${SECRET_KEY}

springdoc:
  swagger-ui:
    path: /

redis:
  host: ${REDIS_HOST}
  port: ${REDIS_PORT}

cloud:
  aws:
    s3:
      bucket: ${AWS_BUCKET}
    region:
      static: ap-northeast-2
    credentials:
      access-key: ${AWS_BUCKET_ACCESS_KEY}
      secret-key: ${AWS_BUCKET_SECRET_KEY}
    stack:
      auto: false